name: üîÅ Sync AynaOTT.m3u to Public Repo

on:
  schedule:
    - cron: "*/30 * * * *"   # ‡¶™‡ßç‡¶∞‡¶§‡¶ø 30 ‡¶Æ‡¶ø‡¶®‡¶ø‡¶ü‡ßá ‡¶∞‡¶æ‡¶® ‡¶π‡¶¨‡ßá
  workflow_dispatch:

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v4

      - name: Configure Git Identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Clone Public Repo
        run: |
          git clone https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/Moniruliptv/AynaOTT_Auto_Update_playlist.git public_repo

      - name: Copy AynaOTT.m3u File
        run: |
          cp AynaOTT.m3u public_repo/

      - name: Push to Public Repo
        run: |
          cd public_repo
          git add AynaOTT.m3u
          git commit -m "Auto update AynaOTT.m3u" || echo "No changes"
          git push
